<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPDu8W0f\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPDu8W0f/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPDu8W0f.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPDu8W0f\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPDu8W0f\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PDu8W0f',
    'container.build_id' => 'dc3fc3b4',
    'container.build_time' => 1636382564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPDu8W0f');
